Repository redvanworkshop/rvw_developers_core, pull requests merged in 2020-11, with the labels that each got.

#17 Updated File Save Method
  .eslintrc.js
  README.md
  cartridges/rvw_dev_console/cartridge/client/default/img/modified.ico
  cartridges/rvw_dev_console/cartridge/client/default/js/vue/components/App.vue
  cartridges/rvw_dev_console/cartridge/client/default/scss/_monaco.scss
  cartridges/rvw_dev_console/cartridge/client/default/scss/_responsive.scss
  cartridges/rvw_dev_console/cartridge/client/default/scss/_split-pane.scss
  cartridges/rvw_dev_console/cartridge/client/default/scss/_theme-hc-black.scss
  cartridges/rvw_dev_console/cartridge/client/default/scss/_theme-vs-dark.scss
  cartridges/rvw_dev_console/cartridge/client/default/scss/_theme.scss
  cartridges/rvw_dev_console/cartridge/client/default/scss/_tree-view.scss
  cartridges/rvw_dev_console/cartridge/static/default/css/dev_console.css
  cartridges/rvw_dev_console/cartridge/static/default/img/modified.ico
  cartridges/rvw_dev_console/cartridge/static/default/js/dev_console.js
  cartridges/rvw_dev_console/cartridge/templates/default/dev_console/index.isml
  package-lock.json
  package.json
Labels: In Code Review

#20 User Authentication & Misc Cleanup
  .circleci/config.yml
  .eslintrc.js
  README.md
  cartridges/rvw_dev_console/cartridge/client/default/js/vue/components/App.vue
  cartridges/rvw_dev_console/cartridge/client/default/js/vue/components/Modal.vue
  cartridges/rvw_dev_console/cartridge/client/default/scss/_modal.scss
  cartridges/rvw_dev_console/cartridge/client/default/scss/_monaco.scss
  cartridges/rvw_dev_console/cartridge/client/default/scss/_toast.scss
  cartridges/rvw_dev_console/cartridge/controllers/Console.js
  cartridges/rvw_dev_console/cartridge/static/default/css/dev_console.css
  cartridges/rvw_dev_console/cartridge/static/default/js/dev_console.js
  package-lock.json
  package.json
Labels: Ready For Code Review

#22 add execution time
  .gitattributes
  .gitignore
  cartridges/rvw_dev_console/cartridge/client/default/js/dev_console.js
  cartridges/rvw_dev_console/cartridge/client/default/js/vue/components/App.vue
  cartridges/rvw_dev_console/cartridge/client/default/scss/_responsive.scss
  cartridges/rvw_dev_console/cartridge/client/default/scss/_util.scss
  cartridges/rvw_dev_console/cartridge/controllers/Console.js
  cartridges/rvw_dev_console/cartridge/static/default/css/dev_console.css
  cartridges/rvw_dev_console/cartridge/static/default/js/dev_console.js
  package-lock.json
  package.json
  webpack.config.js
Labels: Ready For Code Review

#27 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Closed & Merged

#26 GitHub Actions
  .github/cla/agreement.md
  .github/cla/signatures.json
  .github/workflows/assign_to_project.yml
  .github/workflows/build_and_test.yml
  .github/workflows/cla.yml
Labels: Closed & Merged
